Updated CI

diff --git a/scripts/run/set_folder b/scripts/run/set_folder
--- a/scripts/run/set_folder
+++ b/scripts/run/set_folder
@@ -53,7 +53,7 @@ printf "Moving to\n\t%s\n" "$(tput_file "${folder}" 5)"
 
 # Check if the shell is run from vscode
 if [[ ! "${TERM_PROGRAM}" == "vscode" ]]; then
-    cd "${folder}" && echo "Success for \$TERM_PROGRAM: $TERM_PROGRAM" || echo "Failed for \$TERM_PROGRAM: $TERM_PROGRAM"
+    cd "${folder}" || echo "Failed cd'ing to ${folder}"
 else
     code -r "${folder}"
 fi
