Submodules & Streamlining

diff --git a/scripts/build/install_vscode-server b/scripts/build/install_vscode-server
--- a/scripts/build/install_vscode-server
+++ b/scripts/build/install_vscode-server
@@ -1,17 +1,16 @@
 #!/bin/bash
 
-$(
-    cd "$(dirname "${BASH_SOURCE[0]}")" &&
-        chmod u+rwx ./download-vs-code-server &&
-        echo "Installing vscode-server..." &&
-        ./download-vs-code-server >vscode-server.log 2>&1 &&
-        (
-            echo "... successful!" &&
-                rm -rf vscode-server.log
-        ) ||
-        (
-            sed -i 's/^/\t/' vscode-server.log && echo "failed:\n" &&
-                cat vscode-server.log &&
-                exit 1
-        )
-)
+current_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+
+chmod u+rwx "${current_dir}/download-vs-code-server" &&
+    echo "Installing vscode-server..." &&
+    ${current_dir}/download-vs-code-server >${current_dir}/vscode-server.log 2>&1 &&
+    (
+        echo "... successful!" &&
+            rm -rf ${current_dir}/vscode-server.log
+    ) ||
+    (
+        sed -i 's/^/\t/' ${current_dir}/vscode-server.log && echo "failed:\n" &&
+            cat ${current_dir}/vscode-server.log &&
+            exit 1
+    )
